version: '2'
services:

  php-apache:
    image: php/apache:7.0.16
    build: .
    volumes:
      # プログラムファイルのマウント
      - /Users/yuki.tominaga/Documents/research:/var/www/html
    ports:
      - "127.0.0.1:80:80"
    tty: true
    networks:
      apache_net:
        ipv4_address: 172.20.0.2
    container_name: php-apache

  mysql-server:
    image: mysql-server:5.6.29
    build: ./mysql
    volumes:
      # ホストのディレクトリ:コンテナ内のディレクトリ
      # TODO: 任意のローカルディレクトリに変更する
      - /Users/yuki.tominaga/Documents/research/mysql:/var/lib/mysql
      # プログラムファイルのマウント mysql sourceコマンドのため
      # TODO: 任意のローカルディレクトリに変更する
      - /Users/yuki.tominaga/Documents/research:/var/www/html
    environment:
      - MYSQL_ROOT_PASSWORD=cbase3554
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      apache_net:
        ipv4_address: 172.20.0.3
    container_name: mysql-server

  redis:
    image: redis:3.2.5-alpine
    tty: true
    networks:
      apache_net:
        ipv4_address: 172.20.0.4
    container_name: redis-server

  mailcatcher:
    image: tophfr/mailcatcher
    tty: true
    ports:
      - "127.0.0.1:1080:80"
    networks:
      apache_net:
        ipv4_address: 172.20.0.5
    container_name: mailcatcher-server

networks:
  # コンテナのipアドレスは同一サブネット内であればなんでもいい
  apache_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/28
        gateway: 172.20.0.1